name: 3 ) Terraform Apply

on:
  workflow_dispatch:
    inputs:
      confirm_apply:
        description: 'Type "apply" to confirm deployment'
        required: true
        type: string
      env:
        description: "Environment"
        required: true
        type: choice
        options: [dev, prod]
        default: dev

permissions:
  contents: read
  id-token: write

jobs:
  terraform_apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_apply == 'apply'
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.x"

      # Optional (not strictly needed when applying a saved plan)
      - name: Download tfvars from S3
        run: |
          mkdir -p workspace
          aws s3 cp "s3://${{ secrets.TERRAFORM_STATE_BUCKET }}/env/${{ github.event.inputs.env }}.tfvars" \
                    "workspace/${{ github.event.inputs.env }}.tfvars"
          ls -l workspace || true

      - name: Terraform init (remote backend)
        run: terraform init -reconfigure -input=false

      - name: Workspace select/create
        run: terraform workspace select -or-create=true "${{ github.event.inputs.env }}"

      - name: Download plan from S3 (per-environment)
        run: |
          aws s3 cp "s3://${{ secrets.TERRAFORM_STATE_BUCKET }}/plans/${{ github.event.inputs.env }}/tfplan" "tfplan"
          test -s tfplan || { echo "::error::No terraform plan found for ${{ github.event.inputs.env }}. Run the Plan workflow first."; exit 1; }

      - name: Terraform apply (using saved plan)
        run: terraform apply -input=false -auto-approve tfplan
