name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      confirm_apply:
        description: 'Type "apply" to confirm deployment'
        required: true
        type: string
      env:
        description: "Environment"
        required: true
        type: choice
        options: [dev, prod]
        default: dev

permissions:
  contents: read
  id-token: write

jobs:
  terraform_apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_apply == 'apply'

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_OIDC_ROLE_NAME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download tfvars from S3
        run: |
          mkdir -p env
          aws s3 cp "s3://${{ secrets.TERRAFORM_STATE_BUCKET }}/env/${{ github.event.inputs.env }}.tfvars" \
                    "env/${{ github.event.inputs.env }}.tfvars"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.x"

      - name: Terraform init
        run: |
          terraform init -input=false \
            -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
            -backend-config="key=${{ github.event.inputs.env }}/terraform.tfstate" \
            -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Workspace select/create
        run: terraform workspace select -or-create=true "${{ github.event.inputs.env }}"

      - name: Download plan from S3
        run: |
          # Matches the Plan workflow's upload: s3://<bucket>/tfplan
          aws s3 cp "s3://${{ secrets.TERRAFORM_STATE_BUCKET }}/tfplan" "tfplan"
          test -f tfplan || { echo "::error::No terraform plan found. Run the Terraform Plan workflow first."; exit 1; }

      - name: Terraform apply (using saved plan)
        run: terraform apply -input=false -auto-approve tfplan
